import { create } from 'zustand'
import { storage, STORAGE_KEYS } from '@/shared/lib/storage'

/**
 * ISR generated by an approved vacation receipt that has NOT yet been collected.
 * It is collected on the next 2nd-fortnight payroll (regular ISR + this pending amount).
 * Persisted to 'pending_vacation_isr' as { [bamboohrId]: PendingVacationIsr }.
 */
export interface PendingVacationIsr {
  amount: number
  vacationReceiptId: string
  approvedDate: string          // YYYY-MM-DD
  vacationPeriod: string        // e.g. "Apr 1 - Apr 11, 2026"
  appliedInPeriod: string | null // "start/end" once collected; null while pending
}

type PendingStore = Record<string, PendingVacationIsr>

interface PendingVacationIsrState {
  pending: PendingStore
  /** The record for an employee (applied or not). */
  get: (employeeId: string) => PendingVacationIsr | null
  /** Pending (uncollected) ISR for an employee, or null. */
  getUnapplied: (employeeId: string) => PendingVacationIsr | null
  setPending: (employeeId: string, record: PendingVacationIsr) => void
  markApplied: (employeeId: string, period: string) => void
}

export const usePendingVacationIsrStore = create<PendingVacationIsrState>((set, get) => ({
  pending: storage.get<PendingStore>(STORAGE_KEYS.PENDING_VACATION_ISR) ?? {},

  get: (employeeId) => get().pending[employeeId] ?? null,

  getUnapplied: (employeeId) => {
    const r = get().pending[employeeId]
    return r && r.appliedInPeriod === null ? r : null
  },

  setPending: (employeeId, record) => {
    const pending = { ...get().pending, [employeeId]: record }
    storage.set(STORAGE_KEYS.PENDING_VACATION_ISR, pending)
    set({ pending })
  },

  markApplied: (employeeId, period) => {
    const existing = get().pending[employeeId]
    if (!existing || existing.appliedInPeriod !== null) return
    const pending = { ...get().pending, [employeeId]: { ...existing, appliedInPeriod: period } }
    storage.set(STORAGE_KEYS.PENDING_VACATION_ISR, pending)
    set({ pending })
  },
}))
