import { create } from 'zustand'
import { storage, STORAGE_KEYS } from '@/shared/lib/storage'
import { saveAppState, fetchAppState } from '@/shared/lib/cloudSync'
import { cloudWinsMerge } from '@/shared/lib/cloudMerge'

/**
 * ISR generated by an approved vacation receipt that has NOT yet been collected.
 * It is collected on the next 2nd-fortnight payroll (regular ISR + this pending amount).
 * Persisted to 'pending_vacation_isr' as { [bamboohrId]: PendingVacationIsr }.
 */
export interface PendingVacationIsr {
  amount: number
  vacationReceiptId: string
  approvedDate: string          // YYYY-MM-DD
  vacationPeriod: string        // e.g. "Apr 1 - Apr 11, 2026"
  appliedInPeriod: string | null // "start/end" once collected; null while pending
}

type PendingStore = Record<string, PendingVacationIsr>

interface PendingVacationIsrState {
  pending: PendingStore
  /** The record for an employee (applied or not). */
  get: (employeeId: string) => PendingVacationIsr | null
  /** Pending (uncollected) ISR for an employee, or null. */
  getUnapplied: (employeeId: string) => PendingVacationIsr | null
  setPending: (employeeId: string, record: PendingVacationIsr) => void
  markApplied: (employeeId: string, period: string) => void
  /** Read pending-vacation-ISR back from Supabase (cloud-authoritative) and merge. */
  hydrateFromCloud: () => Promise<void>
}

export const usePendingVacationIsrStore = create<PendingVacationIsrState>((set, get) => ({
  pending: storage.get<PendingStore>(STORAGE_KEYS.PENDING_VACATION_ISR) ?? {},

  get: (employeeId) => get().pending[employeeId] ?? null,

  getUnapplied: (employeeId) => {
    const r = get().pending[employeeId]
    return r && r.appliedInPeriod === null ? r : null
  },

  setPending: (employeeId, record) => {
    const pending = { ...get().pending, [employeeId]: record }
    storage.set(STORAGE_KEYS.PENDING_VACATION_ISR, pending)
    set({ pending })
    void saveAppState(STORAGE_KEYS.PENDING_VACATION_ISR, pending)  // best-effort cloud mirror
  },

  markApplied: (employeeId, period) => {
    const existing = get().pending[employeeId]
    if (!existing || existing.appliedInPeriod !== null) return
    const pending = { ...get().pending, [employeeId]: { ...existing, appliedInPeriod: period } }
    storage.set(STORAGE_KEYS.PENDING_VACATION_ISR, pending)
    set({ pending })
    void saveAppState(STORAGE_KEYS.PENDING_VACATION_ISR, pending)  // best-effort cloud mirror
  },

  // Cloud-authoritative read-back: cloud wins per employee key; local-only records are
  // kept and pushed up. Offline-safe (null cloud → local kept).
  hydrateFromCloud: async () => {
    const cloud = await fetchAppState<PendingStore>(STORAGE_KEYS.PENDING_VACATION_ISR)
    if (!cloud) {
      if (Object.keys(get().pending).length > 0) void saveAppState(STORAGE_KEYS.PENDING_VACATION_ISR, get().pending)
      return
    }
    const { merged, localOnlyKeys } = cloudWinsMerge(get().pending, cloud)
    storage.set(STORAGE_KEYS.PENDING_VACATION_ISR, merged)
    set({ pending: merged })
    if (localOnlyKeys.length > 0) void saveAppState(STORAGE_KEYS.PENDING_VACATION_ISR, merged)
  },
}))
